version: '3.8'

services:
  web:
    build:
      context: ./django_learning
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_learning/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: dbtest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sahil1234
      POSTGRES_HOST_AUTH_METHOD: trust  # Allow all connections without a password (for development only)

    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: